name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Podman
      - name: Set up Podman
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the container image
      - name: Build Container Image
        run: |
          podman build -t ghcr.io/${{ github.repository_owner }}/myapps:latest .

      # Step 4: Tag the image (optional but recommended for versioning)
      - name: Tag Image
        run: |
          podman tag ghcr.io/${{ github.repository_owner }}/myapps:latest ghcr.io/${{ github.repository_owner }}/myapps:${{ github.sha }}

      # Step 5: Push the image to GHCR
      - name: Push Image to GHCR
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/myapps:latest
          podman push ghcr.io/${{ github.repository_owner }}/myapps:${{ github.sha }}

      # Step 6: Verify the image (optional)
      - name: List Images
        run: podman images
